### ISSUE TITLE
Error: Cannot find module 'zlib'. connect@1.9.2 doesn't work with node 0.4.12 as proclaimed in doc.

### ISSUE THREAD

**Issue by jigargosar** [senchalabs/connect#689]
```
jigar@ubuntu:~/node_libs/ls/node_modules/express$ npm ls
express@2.3.10 /home/jigar/node_libs/ls/node_modules/express
├─┬ connect@1.9.2 
│ └── formidable@1.0.11 
├── mime@1.2.6 
└── qs@0.5.0 
jigar@ubuntu:~/node_libs/ls/node_modules/express$ node 
> require("connect");
Error: Cannot find module 'zlib'
    at Function._resolveFilename (module.js:326:11)
    at Function._load (module.js:271:25)
    at require (module.js:355:19)
    at Object.<anonymous> (/home/jigar/node_libs/ls/node_modules/express/node_modules/connect/lib/middleware/compress.js:14:12)
    at Module._compile (module.js:411:26)
    at Object..js (module.js:417:10)
    at Module.load (module.js:343:31)
    at Function._load (module.js:302:12)
    at require (module.js:355:19)
    at Object.compress (/home/jigar/node_libs/ls/node_modules/express/node_modules/connect/lib/connect.js:89:14)
> 
jigar@ubuntu:~/node_libs/ls/node_modules/express$ node -v
v0.4.12
jigar@ubuntu:~/node_libs/ls/node_modules/express$ 

```
